services:
  mystoredb:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - mystore-net
    ports:
      - "5432:5432"
  django:
    build: .
    command: ./entrypoint.sh

    env_file:
      - .env
    depends_on:
      - mystoredb
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - mystore-net
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django
    networks:
      - mystore-net
volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  mystore-net:
    driver: bridge
