databases:
  - name: mystore
    plan: free
    databaseName: mystoredb
    user: mystoreuser
services:
  - type: web
    plan: free
    name: mystore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mystore.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mystore
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
