# Generated by Django 5.1.4 on 2025-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordereditem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
